### PR TITLE
docs: modification to evaluation notebook

### PR DESCRIPTION
**Pull request by jjmachan**
# Description

Changed the evaluation notebook to fix some missing files and added a new benchmarking step so that it shows how to use the `DatasetGenerator` also.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [ ] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by logan-markewich — APPROVED** [review]
This looks good to me, although one question. Is it expected to get 0/5 eval questions correct? 👀

**Comment by ravi03071991** [comment]
@jjmachan, it appears there's an error in the notebook during the benchmarking process. The correct code should be total_correct += eval_result. 

@logan-markewich, this could be the reason you're getting 0/5 correct in your results.

**Comment by ravi03071991** [comment]
@jjmachan, it seems like there's an unnecessary step in both notebooks where you're creating a gpt3 evaluator that isn't being used. If your intention is to show a comparison, consider using gpt3.5-turbo which might provide a more meaningful contrast. When conducting the benchmarking, please use the gpt4 evaluator, unless you are specifically aiming to demonstrate a comparison between gpt3.5 and gpt4 evaluations. Moreover, incorporating benchmarking in the QueryResponse evaluator would enhance the analysis.

**Comment by jjmachan** [comment]
Thanks @ravi03071991 and @logan-markewich for pointing out the issues. I've fixed the bug and using gpt-4 evaluator at the moment. 

> Moreover, incorporating benchmarking in the QueryResponse evaluator would enhance the analysis.
I agree with this part but the `Playground` feature should help here I'm assuming? what do you thinking @ravi03071991

**Comment by ravi03071991** [comment]
> Thanks @ravi03071991 and @logan-markewich for pointing out the issues. I've fixed the bug and using gpt-4 evaluator at the moment.
> 
> > Moreover, incorporating benchmarking in the QueryResponse evaluator would enhance the analysis.
> 
> I agree with this part but the `Playground` feature should help here I'm assuming? what do you think @ravi03071991

@jjmachan , it looks good overall. However, I've noticed that the GPT-3 evaluator and model are still present in the QueryResponse Evaluator notebook. 

Adding benchmarking to the QueryResponse Evaluator notebook can help users understand it better. Even though the Playground is a good place for showing detailed benchmarking, having it in the QueryResponse Evaluator notebook can be very helpful for our users.

**Comment by jjmachan** [comment]
I didn't change the `QueryResponseEvaluator` actually. Only the `ResponseEvaluator`. 

We can think about adding benchmarks actually, which should be useful.

**Pull request merged**
