### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by lilulilulilu**
Traceback (most recent call last):
  File "/cognitive_comp/lilu/chatpdf/chatPDF/main.py", line 9, in <module>
    from llama_index.llms import CustomLLM, CompletionResponse, LLMMetadata
ImportError: cannot import name 'CustomLLM' from 'llama_index.llms'

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [x] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by lilulilulilu** [comment]
Traceback (most recent call last):
  File "/cognitive_comp/lilu/chatpdf/chatPDF/main.py", line 9, in <module>
    from llama_index.llms import CustomLLM, CompletionResponse, LLMMetadata
ImportError: cannot import name 'CustomLLM' from 'llama_index.llms'

**Comment by lilulilulilu** [comment]
fix CustomLLM import error

**Comment by lilulilulilu** [comment]
fix CustomLLM import error

**Comment by lilulilulilu** [comment]
fix CustomLLM import error

**Comment by Disiok** [comment]
Ah thanks for catching this!

**Comment by Disiok** [comment]
I just merged it via https://github.com/jerryjliu/llama_index/pull/6752
(you are missing an import statement here)

**Pull request closed without merging**
