### PR TITLE
fix delete document bug for json indexes

### PR DESCRIPTION
**Pull request by achempak-polymer**
When documents are deleted from an index, they're removed from `index_struct` but not `docstore`. This PR addresses that.

### CODE REVIEW

**Review by jerryjliu — CHANGES_REQUESTED** [review]
thanks - would you mind running the formatter? the import will fail lint checks

**Comment by achempak-polymer** [comment]
@jerryjliu after looking at the docstore code a bit more, am I correct in thinking that docstore is a completely independent object from index_struct now? If so, then I guess the expected behavior when removing a document from an index should be to *not* remove it from the docstore as well, right? In that case, I think it's safe to close this PR. 

Although it might be helpful note somewhere in the documentation or code that calling index.delete() on a document doesn't remove the document from the dosctore of that index (this confused me for a while).

**Comment by jerryjliu** [comment]
@achempak-polymer it's a good point. I think we're still figuring out the best UX for clarifying to users whether delete = delete index or also docstore. will have updates soon

**Comment by Disiok** [comment]
Closing this for now, until we figure out the better UX.

**Pull request closed without merging**
