### PR TITLE
add deepeval integration

### PR DESCRIPTION
**Pull request by ColabDog**
# Description

Adding an integration with LlamaIndex - DeepEval is a unit testing framework for LLMs and specifically RAG applications.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [Y] New feature (non-breaking change which adds functionality)
- [Y] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by logan-markewich** [comment]
@ColabDog thanks for adding this! Super cool, evals are an important topic/tool 💪

Would it be possibly to also craft an example notebook? It would better help to convey how to use this 🙏 just in `docs/examples` somewhere, and then linked in your integration page?

**Comment by ColabDog** [comment]
Sounds great - will do that!

**Comment by logan-markewich** [comment]
@ColabDog another contributor just fixed this actually. I'll merge in the main branch here

**Comment by logan-markewich** [comment]
Merged! Thanks!

**Pull request merged**
