### PR TITLE
keep track of response over refine chunks

### PR DESCRIPTION
**Pull request by logan-markewich**
There's a small bug (or at least I think it's a bug) during the refine process.

If a node is broken into multiple chunks, the previous answer was not being tracked,

Let me know if this was not a bug, but otherwise, I think this should be fixed.

### CODE REVIEW

**Review by jerryjliu — COMMENTED** [review]
oh wow. i think i need better tests for this. one sec, going to go into this fork and play around with tests

**Comment by logan-markewich** [comment]
Good point! I should've added a test or two first lol 

Thanks for taking a look though!

**Comment by jerryjliu** [comment]
> Good point! I should've added a test or two first lol
> 
> Thanks for taking a look though!

yeah i need to switch the mock refine logic to better test this repeated behavior

**Comment by jerryjliu** [comment]
@logan-markewich i ended up using this opportunity to completely revamp the refine unit tests :) hopefully will catch stuff like this in the future

**Pull request merged**
