### PR TITLE
Migrate Response Synthesizer

### PR DESCRIPTION
**Pull request by logan-markewich**
# Description

This PR migrates the response synthesizer to use GPT-3.5-Turbo. In addition, some other changes are included

- remove templates from the wandb callback
- stop silently failing on the wandb callback
- stop using `from_prompt` in tree summarize (this was destroying the chat message template) 

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [x] Tested on tons of response modes and top k's
- [x] I stared at the code and made sure it makes sense

### CODE REVIEW

**Comment by jon-chuang** [comment]
Could you rebase on main? Git diff is muddled.

**Comment by logan-markewich** [comment]
oof it is, what the heck haha

**Comment by logan-markewich** [comment]
oh no its worse hahaha

**Comment by logan-markewich** [comment]
Closing in favour of https://github.com/jerryjliu/llama_index/pull/7150

**Pull request closed without merging**
