### PR TITLE
Support Langchain cache on LLMPredictor

### PR DESCRIPTION
**Pull request by xiaofan-luan**
Caching can be useful if a user frequently queries the same data, for both lowering the cost and accelerate search speed. LangChain supports multiple caching options, including redis cache and GPTCache.

This PR enabled LLMPredictor to support a cache. Later PR will focus on how Indexes are gonna to use the cache

### CODE REVIEW

**Comment by jerryjliu** [comment]
this is great! thanks for making the change, will review soon

**Comment by jerryjliu** [comment]
@xiaofan-luan it looks like it's failing tests, would you be able to fix?

**Comment by xiaofan-luan** [comment]
> 

Yep, let me take a look also, have more test on it

**Comment by xiaofan-luan** [comment]
@jerryjliu 
Pls help on rerun the test, thanks.

**Comment by xiaofan-luan** [comment]
fix all the dependency issue. still have couple of lint issue but might be related to my python environment

**Comment by xiaofan-luan** [comment]
fix all the ut issue, it is very hard to make everything work:
1. Langchain version < 1.5.2 has bugs, and cache is not actually working
2.  mongodb store and faiss has many dependecy issues.
3. python 3.7 and 3.11 is hard to run through lint, python 3.9 works for me.
4. even now there are some lint issues on my laptop, I'm pretty sure it's not due to my pr, here is what I found on my laptop
5. 
gpt_index/utils.py:83: error: Module has no attribute "download"  [attr-defined]
gpt_index/langchain_helpers/sql_wrapper.py:45: error: Incompatible return value type (got "List[ReflectedColumn]", expected "List[Dict[Any, Any]]")  [return-value]
gpt_index/optimization/optimizer.py:64: error: Module has no attribute "download"  [attr-defined]
gpt_index/indices/keyword_table/utils.py:33: error: Module has no attribute "download"  [attr-defined]
gpt_index/indices/common/struct_store/sql.py:38: error: Invalid index type "Optional[str]" for "FacadeDict[str, Table]"; expected type "str"  [index]
tests/indices/struct_store/test_base.py:63: error: Need type annotation for "results"  [var-annotated]
benchmarks/struct_indices/spider/spider_utils.py:38: error: "Engine" has no attribute "execute"  [attr-defined]
benchmarks/struct_indices/spider/generate_sql.py:12: error: Module "tqdm" has no attribute "tqdm"  [attr-defined]
benchmarks/struct_indices/spider/generate_sql.py:118: error: "Engine" has no attribute "execute"  [attr-defined]
benchmarks/struct_indices/spider/evaluate.py:13: error: Module "tqdm" has no attribute "tqdm"  [attr-defined]
Found 10 errors in 9 files (checked 346 source files)

**Comment by xiaofan-luan** [comment]
> 

and langchian 1.5.2 use sqlAlchemy2, takes me some time to fix the compatibility issue

**Comment by jerryjliu** [comment]
> > 
> 
> and langchian 1.5.2 use sqlAlchemy2, takes me some time to fix the compatibility issue

thanks for your patience @xiaofan-luan. no problem, we'll take a stab at bumping up the compatible langchain version and also merging in the sqlalchemy fix

**Comment by jerryjliu** [comment]
@xiaofan-luan i recently landed some changes into main that fixes the langchain import issue

if you want i can take over this PR to merge it

**Comment by jerryjliu** [comment]
(was already in the middle of fixing some of these issue for you so happy to take off your hands :) )

**Review by jerryjliu — APPROVED** [review]

**Comment by jerryjliu** [comment]
@xiaofan-luan merged, thanks for your patience. would love followup PR's / examples on how to use this!

**Comment by xiaofan-luan** [comment]
> 

Sure, we do that and give more test

**Pull request merged**
