### PR TITLE
Drop GPT Prefix 

### PR DESCRIPTION
**Pull request by Disiok**

### CODE REVIEW

**Comment by logan-markewich** [comment]
I feel like this is one of those PRs where you have to trust that the unit tests are doing their jobs 😅

**Comment by Disiok** [comment]
> I feel like this is one of those PRs where you have to trust that the unit tests are doing their jobs 😅

**Comment by Disiok** [comment]
@logan-markewich what might help is verifying that old `GPT....` imports continue to work. That's definitely not captured by tests.

**Comment by logan-markewich** [comment]
Working imports:
`from llama_index import GPTVectorStoreIndex, GPTTreeIndex, GPTSQLStructStoreIndex, GPTKeywordTableIndex, GPTRAKEKeywordTableIndex, GPTSimpleKeywordTableIndex`

Broken imports (I think I got them all?):
`from llama_index import GPTPandasIndex, GPTDocumentSummaryIndex, GPTEmptyIndex`

**Comment by Disiok** [comment]
> Working imports: `from llama_index import GPTVectorStoreIndex, GPTTreeIndex, GPTSQLStructStoreIndex, GPTKeywordTableIndex, GPTRAKEKeywordTableIndex, GPTSimpleKeywordTableIndex, GPTListIndex`
> 
> Broken imports (I think I got them all?): `from llama_index import GPTPandasIndex, GPTDocumentSummaryIndex, GPTEmptyIndex`

Good catch, should be good now.

**Pull request merged**
