### PR TITLE
Add `KuzuGraphStore`

### PR DESCRIPTION
**Pull request by mewim**
# Description

This PR adds `KuzuGraphStore`, which allows using [Kùzu database](https://kuzudb.com) for persisting graphs.

It also fixes an issue in `get_networkx_graph` function. According to https://github.com/jerryjliu/llama_index/blob/dd0bc90810f0b5d702febbe8eaa71e80dec503ad/llama_index/indices/knowledge_graph/retriever.py#L261

The return value from `get_rel_map` should be in the format of `subject [predicate, object, predicate_next_hop, object_next_hop ...]`, which allows more than two values in the list, but `get_networkx_graph` function assumes that each list contains only two values. 

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Added new unit/integration tests
- [x] Added new notebook (that tests end-to-end)
- [x] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by logan-markewich — APPROVED** [review]
This looks pretty good to me, thanks for such a clean PR!

**Comment by logan-markewich** [comment]
@mewim quite a few typing errors before I can merge though :)

**Comment by mewim** [comment]
Hi @logan-markewich,

Thanks for reviewing my PR. I have added the type annotations and made sure that the linting passed locally by running `make lint`.

**Comment by logan-markewich** [comment]
Looks great, thanks @mewim !

**Pull request merged**
