### PR TITLE
Update milvus and add testcases

### PR DESCRIPTION
**Pull request by filip-halt**
# Description

Update Milvus to add compatibility with dynamic schema and filter support. Requires new connection parameters and new collection settings for already existing collections.

## Type of Change

Please delete options that are not relevant.

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Added new unit/integration tests
- [ ] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by logan-markewich** [comment]
This seems like a breaking change, can we mitigate that? 

Also, Can you update the notebook with the proper usage: https://github.com/jerryjliu/llama_index/blob/main/docs/examples/vector_stores/MilvusIndexDemo.ipynb

**Comment by filip-halt** [comment]
> This seems like a breaking change, can we mitigate that?
> 
> Also, Can you update the notebook with the proper usage: https://github.com/jerryjliu/llama_index/blob/main/docs/examples/vector_stores/MilvusIndexDemo.ipynb
> 
> (Edit: just saw the title changed to WIP haha will wait to take a deeper look)

I was debating making it milvus_v2 to trigger a slow movement to it but I think upkeeping both would become a larger hassle than its worth.

Technically most existing collections should work with this switch, but highly custom ones will probably fail.

A quick question @logan-markewich , are retrievers still being used or have we added the ability to wrap all the vector stores into retrievers?

**Comment by logan-markewich** [comment]
@filip-halt yes retrievers are a core abstraction in llamaindex 👍

Was there an additional point of integration you were thinking about? Or some issue with how vector stores are managed in llamaindex?

**Comment by logan-markewich** [comment]
@filip-halt Sorry for the delay on this one!

Can you also update/re-run the milvus notebook as well?

**Comment by filip-halt** [comment]
> @filip-halt Sorry for the delay on this one!
> 
> Can you also update/re-run the milvus notebook as well?
> 
> Should be here: https://gpt-index.readthedocs.io/en/stable/examples/vector_stores/MilvusIndexDemo.html

Done @logan-markewich

**Pull request merged**
