### PR TITLE
more robust default pdf parser

### PR DESCRIPTION
**Pull request by thunderbug1**
# Description

Due to https://github.com/py-pdf/pypdf/issues/1507 it would be good to have a more robust pdf parser.
This parser is based on pdfminer.six which produces better results.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Disiok** [comment]
@thunderbug1 hard to know which pdf parser works better, and in which cases. do you have some insight whether if pdfminer.six is actually better than pypdf across the board?

**Comment by jerryjliu** [comment]
@thunderbug1 regardless of decision, could you help add this to LlamaHub https://github.com/emptycrown/llama-hub/pulls? would be an awesome change

**Comment by thunderbug1** [comment]
@Disiok, I don't have any formal test results but I do see that this parser produces much better results for my documents. Do we have test documents for comparison tests?

**Comment by MartinThoma** [comment]
You might be interested in https://github.com/py-pdf/benchmarks

**Comment by Disiok** [comment]
Since it's been merged in llama hub, and can't seem to find evidence that this works better than pypdf (at least https://github.com/py-pdf/benchmarks doesn't seem to support). Going to close this for now.

**Pull request closed without merging**
