### PR TITLE
Add notebooks to docs

### PR DESCRIPTION
**Pull request by logan-markewich**
Ok, two main imrpvoments here:

1. (EDIT, this is already merged separately) A new template that looks a little more modern, but more importantly, allows you to expand the tree in the sidebar
2. Embeds notebooks. I know this broke some things last time, but I thiiiiink I added the right files this time so that readthedocs autobuild works. The one hard part is I'm not sure how to fully test it (`make html` works fine), since PRs seems to follow a different build process than mainline builds 🤔 

(Side note on the notebooks. Like last time, I had to do some ninja edits to the two notebooks that used the display_response function -- putting markdown linebreaks seems to break nbsphinx parsing)

### CODE REVIEW

**Comment by logan-markewich** [comment]
image

https://gpt-index--1164.org.readthedocs.build/en/1164/

**Comment by jerryjliu** [comment]
Oh wow not only the notebooks but the docs too?? 

Will take a look and play around, thanks @logan-markewich

**Comment by logan-markewich** [comment]
For reference, I followed this guide to try and get sphinx autobuild to work:

https://nbsphinx.readthedocs.io/en/0.9.1/usage.html#Using-conda

I used the conda approach, since that handles the extra dependencies for pandoc that are normally installed with apt-get

**Comment by logan-markewich** [comment]
Also, I've disabled PDF generation for now (since that was breaking last time we tried to merge notebooks)

If you think we need PDF generation, I can try and figure it out lol

Also! I added ranked searches, so that the API references are ranked a little lower in the search (they aren't as helpful as the other docs pags, in my opinion anyways)

**Comment by jerryjliu** [comment]
@logan-markewich just checked the readthedocs links, doesn't seem like notebooks are embedded?

**Comment by logan-markewich** [comment]
@jerryjliu oh what the... I'll figure that out in a sec lol I swore I saw them a few commits ago.

**Comment by jerryjliu** [comment]
> @jerryjliu oh what the... I'll figure that out in a sec lol I swore I saw them a few commits ago.

no worries! take your time

**Comment by logan-markewich** [comment]
There we go, forgot about the pesky gitignore

**Comment by jerryjliu** [comment]
sweet! going to try merging now

**Pull request merged**
