### PR TITLE
supabase vecs

### PR DESCRIPTION
**Pull request by Zanyar261**
This is my first ever commit on something that isn't on my own project. Please pick me apart and tell me everything that is wrong with it (if you have the time).  Did it because of this tweet: https://twitter.com/kiwicopple/status/1664377669935349760 if you need context.
Not sure if it will work but I think it will make it easier

### CODE REVIEW

**Comment by Zanyar261** [comment]
was not on purpose to mark it ready

**Review by jerryjliu — CHANGES_REQUESTED** [review]
hi @Zanyar261, thanks for the submission. We probably don't want new abstractions - could you look at subclassing our VectorStore class? see our implementations for pinecone/chroma/weaviate etc. as an example

**Comment by Zanyar261** [comment]
ok gonna try my best

**Comment by Zanyar261** [comment]
So I have done some different but I definetely reached my newbie limits. Have spend like 4 hours on it together but I learnt so much so thank you for it! The new one is probably also very very wrong so you can ignore it, but at least I tried. I have school holidays so I am gonna spend some time learning to code with this so that I can finally someday really contribute to it. Should I close this pr?

**Comment by Disiok** [comment]
Hey @Zanyar261 , thanks again for your contribution! I think we will close this in favor of merging https://github.com/jerryjliu/llama_index/pull/4759. 

Please do contribute in the future!

**Pull request closed without merging**
