### PR TITLE
default prompt optimize for gpt-3.5-turbo

### PR DESCRIPTION
**Pull request by zombieyang**
related thread in discord:
企业微信截图_8266a52b-d8c9-472b-93f7-acaaaeceeaa2(1)

-------------

I read the contrib.md and ran the tests. But I found that I can't  reproduce this question in the tests without api key. So I just commit the change of the prompt.

If I should do any further work, please tell me.

------------
And I think. If different LLM needs different prompts, different nature language also needs different prompts. Maybe we should build a hub to store all these prompts? Just like the readers.

### CODE REVIEW

**Comment by jerryjliu** [comment]
hi @zombieyang, thanks! actually for chatgpt we make use of PromptSelectors, take a look at `gpt_index/prompts/default_prompt_selectors.py`. basically, for chatgpt models, we use the CHAT_REFINE_PROMPT in `gpt_index/prompts/chat_prompts.py` by default (with its own message types) and not the "base" prompt template

**Comment by zombieyang** [comment]
> hi @zombieyang, thanks! actually for chatgpt we make use of PromptSelectors, take a look at `gpt_index/prompts/default_prompt_selectors.py`. basically, for chatgpt models, we use the CHAT_REFINE_PROMPT in `gpt_index/prompts/chat_prompts.py` by default (with its own message types) and not the "base" prompt template

I've look into the code `gpt_index/prompts/default_prompt_selectors.py` and `gpt_index/prompts/base.py` . It seems that the prompt selecting is a builtin behaviour, am I right? 

and

```
Given the new context, refine the original answer to better answer the question. If the context isn\'t useful, return the original answer."}], "model": "gpt-3.5-turbo", "temperature": 0}'
```
These are what I see in the logger. The prompts match the `default_prompts` instead of `chat_prompts`. So, is these means that the selecting logic going wrong?

**Comment by jerryjliu** [comment]
> > hi @zombieyang, thanks! actually for chatgpt we make use of PromptSelectors, take a look at `gpt_index/prompts/default_prompt_selectors.py`. basically, for chatgpt models, we use the CHAT_REFINE_PROMPT in `gpt_index/prompts/chat_prompts.py` by default (with its own message types) and not the "base" prompt template
> 
> Thanks for your guide! I've look into the code `gpt_index/prompts/default_prompt_selectors.py` and `gpt_index/prompts/base.py` . It seems that the prompt selecting is a builtin behaviour, am I right?
> 
> and
> 
> ```
> Given the new context, refine the original answer to better answer the question. If the context isn\'t useful, return the original answer."}], "model": "gpt-3.5-turbo", "temperature": 0}'
> ```
> 
> These are what I see in the logger. The prompts match the `default_prompts` instead of `chat_prompts`. So, is these means that the selecting logic going wrong?

The CHAT_REFINE_PROMPT looks something like this

```
CHAT_REFINE_PROMPT_TMPL_MSGS = [
    HumanMessagePromptTemplate.from_template("{query_str}"),
    AIMessagePromptTemplate.from_template("{existing_answer}"),
    HumanMessagePromptTemplate.from_template(
        "We have the opportunity to refine the above answer "
        "(only if needed) with some more context below.\n"
        "------------\n"
        "{context_msg}\n"
        "------------\n"
        "Given the new context, refine the original answer to better "
        "answer the question. "
        "If the context isn't useful, output the original answer again.",
    ),
]


CHAT_REFINE_PROMPT_LC = ChatPromptTemplate.from_messages(CHAT_REFINE_PROMPT_TMPL_MSGS)
CHAT_REFINE_PROMPT = RefinePrompt.from_langchain_prompt(CHAT_REFINE_PROMPT_LC)
```

so still contains the part of text that you were describing

**Comment by zombieyang** [comment]
> > > hi @zombieyang, thanks! actually for chatgpt we make use of PromptSelectors, take a look at `gpt_index/prompts/default_prompt_selectors.py`. basically, for chatgpt models, we use the CHAT_REFINE_PROMPT in `gpt_index/prompts/chat_prompts.py` by default (with its own message types) and not the "base" prompt template
> > 
> > 
> > Thanks for your guide! I've look into the code `gpt_index/prompts/default_prompt_selectors.py` and `gpt_index/prompts/base.py` . It seems that the prompt selecting is a builtin behaviour, am I right?
> > and
> > ```
> > Given the new context, refine the original answer to better answer the question. If the context isn\'t useful, return the original answer."}], "model": "gpt-3.5-turbo", "temperature": 0}'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > These are what I see in the logger. The prompts match the `default_prompts` instead of `chat_prompts`. So, is these means that the selecting logic going wrong?
> 
> The CHAT_REFINE_PROMPT looks something like this
> 
> ```
> CHAT_REFINE_PROMPT_TMPL_MSGS = [
>     HumanMessagePromptTemplate.from_template("{query_str}"),
>     AIMessagePromptTemplate.from_template("{existing_answer}"),
>     HumanMessagePromptTemplate.from_template(
>         "We have the opportunity to refine the above answer "
>         "(only if needed) with some more context below.\n"
>         "------------\n"
>         "{context_msg}\n"
>         "------------\n"
>         "Given the new context, refine the original answer to better "
>         "answer the question. "
>         "If the context isn't useful, output the original answer again.",
>     ),
> ]
> 
> 
> CHAT_REFINE_PROMPT_LC = ChatPromptTemplate.from_messages(CHAT_REFINE_PROMPT_TMPL_MSGS)
> CHAT_REFINE_PROMPT = RefinePrompt.from_langchain_prompt(CHAT_REFINE_PROMPT_LC)
> ```
> 
> so still contains the part of text that you were describing

my prompt is ends with `return the original answer.`, not `output the original answer again.`. So I think `default_prompt` is selected in my case.

in llama_index's code, I saw you select `chat_prompt` when`is_chat_model` is True:
```
DEFAULT_REFINE_PROMPT_SEL_LC = ConditionalPromptSelector(
    default_prompt=DEFAULT_REFINE_PROMPT.get_langchain_prompt(),
    conditionals=[(is_chat_model, CHAT_REFINE_PROMPT.get_langchain_prompt())],
)
```
and the definition of `is_chat_model` is 
```
def is_llm(llm: BaseLanguageModel) -> bool:
    return isinstance(llm, BaseLLM)


def is_chat_model(llm: BaseLanguageModel) -> bool:
    return isinstance(llm, BaseChatModel)
```

my LLMPredictor is `LLMPredictor(llm=OpenAI(temperature=0, model_name="gpt-3.5-turbo"))`. And I found that `OpenAI` is derived from `BaseLLM` instead of `BaseChatModel`. So, the select logic is correct.


------------------------
 
Back to the start. What I mean in this PR is: The `default_prompt` is worked well for default LLM model in llama_index (davinci), but me and someone on discord found that in another LLM model `gpt-3.5-turbo`, the `default_prompt` is not working well. 

为了防止是我英文不好产生误会，我写一遍中文：
默认的prompt在默认的davinci LLM下是运作正常的，当我切换成 gpt-3.5-turbo API时，就会在refine的时候出现问题（discord上也有别人出现了）。所以我的PR是想优化一下default_prompt。
另外就是我觉得除了不同LLM可能需要不同prompt，不同的自然语言（中英文）也会需要不同的默认prompt，所以或许一个收集各种prompt的hub是必要的，不知道你怎么想。

Thanks a lot, I love llama_index.

**Pull request closed without merging**
