### PR TITLE
[Hacky] Fix streaming

### PR DESCRIPTION
**Pull request by jerryjliu**
LangChain's callback manager provides an `on_llm_new_token` method that's called for each token returned in a streaming setting.

The challenge with integrating with LlamaIndex is that we only want `on_llm_new_token` to be called for the *final* response,
rather than for every intermediate response. This notebook below shows you how to set that up.

Key components:
- `ChatOpenAI` LLM class with `streaming=True`
- `ChatGPTLLMPredictor` with LLM and `CallbackManager` specified
- call `index.query` with `streaming=True`

A few notes:
- We've provided a demo `StreamStdoutCallbackHandler` that outputs tokens to stdout, but would highly encourage you to develop your own CallbackHandler

Tbh this solution is pretty hacky - for composed graphs it will still stream "multiple" intermediate responses. 
This API will probably change in the near future

### CODE REVIEW

**Comment by fengjial** [comment]
hi jerryjliu,
i merge your patch to my local, and try to get stream with openai. but this patch seams not work.
here is my code:
    llm = ChatOpenAI(model_name="gpt-3.5-turbo", temperature=0.5, streaming=True)
    callback_manager = CallbackManager(handlers=[StreamStdoutCallbackHandler()])
    llm_predictor = ChatGPTLLMPredictor(llm=llm, callback_manager=callback_manager)
    service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor)
    index = GPTSimpleVectorIndex.load_from_disk(index_file, service_context=service_context)
    response = index.query(query, service_context=service_context,
                streaming=True)
i got error:
DEBUG in app: 'Response' object has no attribute 'print_response_stream'
it seam index.query return Response insteadof StreamingResponse. 
Any idea for this?

**Comment by nhatquang238** [comment]
@jerryjliu I tested this PR out on my local. For text smaller than the max_input_size, everything worked fine. 

However, when the text to be passed to LLM is longer than max_input_size, this particular line https://github.com/jerryjliu/llama_index/blob/jerry/fix_streaming/gpt_index/llm_predictor/chatgpt.py#L144 creates a bug in this line https://github.com/hwchase17/langchain/blob/master/langchain/chat_models/base.py#L75 since self.callback_manager is now None.

For context, here is my service_context setup:

```
        max_input_size = 4096
        num_tokens = 512
        max_chunk_overlap = 20
        prompt_helper = PromptHelper(max_input_size, num_tokens, max_chunk_overlap)
        callback_manager = CallbackManager([
            CustomCallbackHandler()
        ])
        llm=ChatOpenAI(
            temperature=0.7,
            model_name="gpt-3.5-turbo",
            max_tokens=num_tokens,
            streaming=True
        )

        llm_predictor = ChatGPTLLMPredictor(llm=llm, callback_manager=callback_manager)
        service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, prompt_helper=prompt_helper)
```

**Comment by WongSaang** [comment]
Thank you for your hard work. Looking forward to this feature being merged🤪

**Comment by jerryjliu** [comment]
> @jerryjliu I tested this PR out on my local. For text smaller than the max_input_size, everything worked fine.
> 
> However, when the text to be passed to LLM is longer than max_input_size, this particular line https://github.com/jerryjliu/llama_index/blob/jerry/fix_streaming/gpt_index/llm_predictor/chatgpt.py#L144 creates a bug in this line https://github.com/hwchase17/langchain/blob/master/langchain/chat_models/base.py#L75 since self.callback_manager is now None.
> 
> For context, here is my service_context setup:
> 
> ```
>         max_input_size = 4096
>         num_tokens = 512
>         max_chunk_overlap = 20
>         prompt_helper = PromptHelper(max_input_size, num_tokens, max_chunk_overlap)
>         callback_manager = CallbackManager([
>             CustomCallbackHandler()
>         ])
>         llm=ChatOpenAI(
>             temperature=0.7,
>             model_name="gpt-3.5-turbo",
>             max_tokens=num_tokens,
>             streaming=True
>         )
> 
>         llm_predictor = ChatGPTLLMPredictor(llm=llm, callback_manager=callback_manager)
>         service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, prompt_helper=prompt_helper)
> ```

thanks for flagging @nhatquang238, will try to take a look soon

**Comment by reinershir** [comment]
it's does't work

my code:
```python
from llama_index import SimpleDirectoryReader, ServiceContext, GPTSimpleVectorIndex, PromptHelper,QueryMode
from llama_index.llm_predictor.chatgpt import ChatGPTLLMPredictor
from langchain.chat_models import ChatOpenAI
import os
from langchain.callbacks.base import (
    CallbackManager
)
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler

os.environ["OPENAI_API_KEY"] = 'xxx'

def construct_index(directory_path):
    # set maximum input size
    max_input_size = 4096
    # set number of output tokens
    num_outputs = 2000
    # set maximum chunk overlap
    max_chunk_overlap = 20
    # set chunk size limit
    chunk_size_limit = 2000 

    callback_manager = CallbackManager(handlers=[StreamingStdOutCallbackHandler()])
    # define LLM
    llm_predictor = ChatGPTLLMPredictor(llm=ChatOpenAI(temperature=0.5, model_name="gpt-3.5-turbo", streaming=True,callback_manager=callback_manager))
    prompt_helper = PromptHelper(max_input_size, num_outputs, max_chunk_overlap, chunk_size_limit=chunk_size_limit)
 
    documents = SimpleDirectoryReader(directory_path).load_data('')
    service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, prompt_helper=prompt_helper)
    index = GPTSimpleVectorIndex.from_documents(documents,service_context=service_context)

    index.save_to_disk('D://index.json')

    return service_context

def ask_ai(service_context):
    index = GPTSimpleVectorIndex.load_from_disk('D://index.json')

    while True: 
        query = input("What do you want to ask? ")
        response = index.query(query, response_mode=QueryMode.DEFAULT)
        print(response)
        response.print_response_stream()



service_context=construct_index('D://GPTIndex_Traning')
ask_ai(service_context)
```
When I run this code, I get the following error:
AttributeError: 'Response' object has no attribute 'print_response_stream'

version:
llama_index version: 0.5.25
python version: 3.10.9

how to use streaming?

**Comment by Disiok** [comment]
Closing in favor of https://github.com/jerryjliu/llama_index/pull/1059

**Pull request closed without merging**
