### PR TITLE
Add native huggingface embeddings

### PR DESCRIPTION
**Pull request by logan-markewich**
# Description

This PR adds native huggingface embedding support, including
- Generic huggingface models (cls and mean pooling)
- Instructor embeddings
- Optimum embeddings for ONNX support (cls and mean pooling)

## Type of Change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [x] Added new notebook (that tests end-to-end)
- [x] I stared at the code and made sure it makes sense

### CODE REVIEW

**Review by jerryjliu — COMMENTED** [review]
not necc in this PR. in a later PR just flagging we can change all notebook references from LangchainEmbedding as well.

just did a `grep -r "LangchainEmbedding" *` in `docs/examples`

**Comment by logan-markewich** [comment]
I did some extra tests. These configs give the exact same response and similarity scores

```python
from llama_index import ServiceContext
from llama_index.embeddings import HuggingFaceEmbedding, LangchainEmbedding
from llama_index.bridge.langchain import HuggingFaceBgeEmbeddings

embed1 = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")
embed2 = LangchainEmbedding(langchain_embeddings=HuggingFaceBgeEmbeddings(model_name="BAAI/bge-small-en-v1.5"))

ctx1 = ServiceContext.from_defaults(embed_model=embed1)
ctx2 = ServiceContext.from_defaults(embed_model=embed2)

index1 = VectorStoreIndex.from_documents(documents, service_context=ctx1)
index2 = VectorStoreIndex.from_documents(documents, service_context=ctx2)
```

**Review by jerryjliu — APPROVED** [review]
thanks! sorry for slight delay on this, was reviewing this in bits and pieces.

In the notebook, might be good to have captions on what each model does and differences if that's available (hf vs. instructor vs. onnx)

**Review by Disiok — APPROVED** [review]
Wow I love this PR. Thanks @logan-markewich!!!

**Pull request merged**
