### PR TITLE
fix: Connection Session Management on Postgres Vector Store

### LINKED ISSUE #6821: [Bug]: PGVectorStore stop inserting data after queried/retrieved
### Bug Description

PGVectorStore stops inserting data after being queried/retrieved, and start to work again after restarted.

Sorry I'm bad at describing, but you can see what I mean from the "Step to Reproduce" below.

### Version

0.7.4

### Steps to Reproduce

1. Create a PGVectorStore Index with empty documents
```
vector_store = PGVectorStore.from_params()
storage_ctx = StorageContext.from_defaults(vector_store=vector_store)
index = VectorStoreIndex([], storage_context=storage_ctx)
```
2. Go to your database and check the number of rows on the index table, should be zero
3. Insert some documents ad observe the number of rows. At this point, the rows still added
```
for doc in documents:
    index.insert(doc)
```
4. Create a retriever and retrieve some data.
```
retriever = index.as_retriever()
result = retriever.retrieve("keyword")
```
5. Insert additional documents ad observe the number of rows. At this point, the number of rows won't change
6. Restart the service, and it will work again, but the data you insert after the `.retrieve()` won't be there.

Another way to test is, you can insert a long list of documents, and then call query/retrieve in the middle of the insertion process. You'll notice the rows stop being added to the table once you call query/retrieve.

### Relevant Logs/Tracbacks

_No response_

### PR DESCRIPTION
**Pull request by rendyfebry**
# Description

Improve connection session management on Postgres Vector Store

Fixes #6821

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] Added new unit/integration tests
- [X] Run existing unit test
- [ ] Added new notebook (that tests end-to-end)

# Suggested Checklist:

- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Disiok — COMMENTED** [review]
Could you briefly explain the change (e.g. what new feature or bug this fixes). Would really help reviewing! Thanks.

**Comment by rendyfebry** [comment]
Hi @Disiok 

Honestly since I'm not sure what actually happened, since I'm not an expert in python nor SQLAlchemy.

But when I played around with the PostgrestVectorStore, I found this #6821 bug, and the change I made here solved the bug.

My first assumption is the bug caused by dirty session management. As I explain on the bug page, SupabaseVectorStore, so I follow their connection management and implemented it here. And it solves the bug.

https://github.com/supabase/vecs/blob/095b3c3bea872786f6666877de3f2184bb03e6a7/src/vecs/collection.py#L292

**Comment by rendyfebry** [comment]
Oh also, the delete function on the PostgreVectorStore is actually failing after the ref_doc_id implementation.

Probably no one noticed this before because the use test will be skipped if no RDS database is supplied when executing the test.

This PR also solves this delete function issue.

**Comment by rendyfebry** [comment]
The linting failed because the line is too long, but I don't think there's a way make it shorter
```
f"DELETE FROM public.data_{self.table_name} where (metadata_->>'doc_id')::text = '{ref_doc_id}' "
```

Any idea @Disiok, or can we ignore this for now?

**Comment by logan-markewich** [comment]
@rendyfebry actually I was just going to ask about this line

How is it working? Since the metadata does not store a `doc_id` attribute. Instead, the schema should probably be specifically storing `node.ref_doc_id` for this to work 🤔

**Comment by logan-markewich** [comment]
@rendyfebry For some reason I can't push to the PR branch, but you can just split that line into two lines

```python
                stmt = sqlalchemy.text(
                    f"DELETE FROM public.data_{self.table_name} where "
                    f"(metadata_->>'doc_id')::text = '{ref_doc_id}' "
                )
```

Can you also update the changelog? I'll merge once that is done 👍🏻

**Comment by rendyfebry** [comment]
Thank's @logan-markewich It works. Feel free to check again.

**Pull request merged**
