### PR TITLE
Vectara integration

### PR DESCRIPTION
**Pull request by ofermend**
# Description

Integration of Vectara with Llama_index.

## Type of Change

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [X] Added new unit/integration tests
- [X] Added new notebook (that tests end-to-end)

# Suggested Checklist:

- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by jerryjliu** [comment]
exciting!

**Comment by ofermend** [comment]
@jerryjliu - for sure. Let me know your thoughts:
- Vectara is not just a vector database, as you may know, so includes additional functionality out of the box.
- For example when you index text, it's automatically broken down into "chunks" in the backend. So I wasn't sure how to deal with the inherent "nodes" in LI. See the current initial proposal in this where add_documents instead of the usual add(). Would love your guidance wrt if this is the best way given current design of LI.

**Comment by ofermend** [comment]
@jerryjliu - checking in on this? Any thoughts / guidance on next steps for this PR?

**Comment by ofermend** [comment]
Yes agree #2 is more clean. Let me look into that.

**Comment by ofermend** [comment]
So this would be a new folder (let's say "vectara") under "llama_index/indices", similar to say "list" or "tree" that has base and retreivers like the other types of indices? Just making sure that's what you had in mind...

**Comment by logan-markewich** [comment]
(Whoops, this got rather long, sorry about the wall of text LOL)

@ofermend Well actually, what I had in mind was slightly different.

So what I was originally thinking was that `llama_index/storage/docstore` would have a new file for vectara, to handle the `add_documents` feature. Then `llama_index/retrievers` would have a new file for retrieving from an existing vectara index. Code flow might look something like this?

```python
documents = SimpleDirectoryReader("./data").load_data()

docstore = VectaraDocStore.add_documents(documents)

# this could take a docstore, or just parameters to connect to an existing index?
retriever = VectaraRetriever(docstore=docstore)

# use as a retriever for fetching nodes?
nodes = retriever.retrieve("query")

# use as part of a query engine for synthesizing natural language answers
query_engine = RetrieverQueryEngine(retriever)
response = query_engine.query("query")
```

------------------------
Although thinking on it a bit, there is another option 🧠 

So the thing is, we want to keep things as general as possible. For example, having an index specific to vector that doesn't act anywhere near other indexes feels a little out of place? For example, this index would not be using the storage context (docstore, vector store, or index store), which might be unexpected for users?

But on the other hand, what if there was a new category of index -- `APIIndex` (? that's a terrible name lol), that was something that we could extend to other services that act more like an index (vectara, marqo, and I'm sure others). This index class could then be extended for vectara then. Although, I'm still not sure if it could actually extend our `BaseIndex` class, or if it would have to be its own base class?

**Comment by ofermend** [comment]
@logan-markewich - yes agreed (and thanks; this is helpful discussion as you have more expertise on the llama_index architecture and design than me).

I think what you suggest is best, and that's actually what I had in mind, I was just not aware of others that could fit this category - so generalizing makes a ton of sense. 

Perhaps I can suggest "ManagedIndex" (meaning it's not stored locally and used via a managed service accessible via an API). 

If we go with that:
1. It's similar to what I was suggesting, only instead of a new "vectara" folder for a new type of index, we generalize to "Managed" under /indices and build that initial baseline
2. Then vectara would be the initial ManagedIndex (or whatever we choose to call it); where would you suggest we put that specific implementation of a Managed Index?

**Comment by logan-markewich** [comment]
@ofermend yea so in my mind, I thiiiink it would look something like this (undecided if the base class is actually needed or not, or if extending `BaseIndex` flat out could work?

```
llama_index/
|_ indices/
    |_ managed/
        |_ base.py -- some kind of base class to extend?
        |_ vectara/
            |_ base.py -- actual index
            |_ retriever.py -- specific retriever for vectara
```

With this setup, you could still do `index.as_retriever()` and `index.as_query_engine()`, as well as use the query engine/retriever in our other abstractions 👍🏻 

Also very relevant, I can probably point this PR in the same direction once this is merged https://github.com/jerryjliu/llama_index/pull/7023

With more than one managed index, it makes sense to make this it's own category

**Comment by ofermend** [comment]
Thanks. That makes sense - sorry been busy but hope to get to do this in this manner soon.

**Comment by logan-markewich** [comment]
No worries, sounds good!

**Comment by ofermend** [comment]
@logan-markewich - just submitted https://github.com/jerryjliu/llama_index/pull/7423
Please take a look and let me know if this is roughly what you had in mind for Managed Index.

**Pull request closed without merging**
