### PR TITLE
docs: Add CoFounder to App Showcase gallary

### PR DESCRIPTION
**Pull request by seawatts**
[CoFounder](https://co-founder.ai?utm_source=llama-index&utm_medium=gallary&utm_campaign=alpha) is a platform to revolutionize the start-up ecosystem by providing founders with unparalleled tools, resources, and support. We are changing how founders build their companies from 0-1—productizing the accelerator/incubator programs using AI.

We are starting with the following features:

* AI Investor Matching and Introduction and Tracking
* AI Pitch Deck creation
* Real-time Pitch Deck practice/feedback
* Automatic Competitive Analysis / Watchlist

It uses LlamaIndex to create a context for each company on the platform. Our algorithms then use it to create recommendations for the founders and investors.

### CODE REVIEW

**Comment by Disiok** [comment]
Hey @seawatts  thanks for the PR. Could you say more about what the app does. Also curious how does it use LlamaIndex?

**Comment by seawatts** [comment]
Hey @Disiok, thanks for the quick comment! I just updated the description. Thanks.

**Comment by Disiok** [comment]
> Hey @Disiok, thanks for the quick comment! I just updated the description. Thanks.

Think you might've forgotten to push the changes?

**Comment by seawatts** [comment]
@Disiok pushed!

**Review by jerryjliu — APPROVED** [review]

**Pull request merged**
