### PR TITLE
Add custom LLM example

### PR DESCRIPTION
**Pull request by logan-markewich**
This question gets asked fairly frequently, so it would be helpful to have a docs page to point at.

Especially with the recent Llama/Alpaca developments, I think this is going to be a more popular option going forward.

### CODE REVIEW

**Review by jerryjliu — APPROVED** [review]
this is great!! does this work / did you test the example?

**Comment by logan-markewich** [comment]
I tested it about a month ago. Let me double check that it still works lol

**Comment by logan-markewich** [comment]
Actually, I should also add the prompt helper to the example too (since FLAN has a lower output/input size)

**Comment by logan-markewich** [comment]
Ok, improved the example. Switched to Facebook's OPT-IML model which is a more realistic (and not legally-gray model like 🦙 ) example.

**Review by jerryjliu — APPROVED** [review]

**Pull request merged**
