### PR TITLE
Will/add confluence reader

### PR DESCRIPTION
**Pull request by zywilliamli**
adds a data connector for confluence, given a space id and/or a list of page ids

not sure if I need to add any docs or examples, please instruct :)

### CODE REVIEW

**Review by jerryjliu — COMMENTED** [review]
@zywilliamli this is great!! any chance you could port over this PR to a loader on llama-hub instead? https://github.com/emptycrown/llama-hub llama-hub is the main hub containing our data loaders:
- create confluence folder,
- add the following files: __init__.py, base.py, requirements.txt, README.md

you can follow other examples to see how to format it, hopefully shouldn't be too much of a change from what you have already

**Comment by zywilliamli** [comment]
no worries, didn't know it's on llama-hub now. i'll move it over

**Comment by zywilliamli** [comment]
raised a pr here: https://github.com/emptycrown/llama-hub/pull/135

**Comment by jerryjliu** [comment]
@zywilliamli should we close now?

**Pull request closed without merging**
