### PR TITLE
🌟 MyScale VectorStore Support to LlamaIndex

### PR DESCRIPTION
**Pull request by Nonegrace**
# [MyScale](https://myscale.com) Vector Store

MyScale is a high-performance SQL + Vector OLAP database built on ClickHouse.  You can find more details on [MyScale's website](https://myscale.com)

## 📚 How to use

1. Go to [MyScale](https://myscale.com) and click on sign up.
2. Go to your console to [create a cluster](https://docs.myscale.com/en/cluster-management/)
3. Get your `Connection Details` under `Action` column under cluster table.
4. Create a MyScale Client with your connection details

```python
import clickhouse_connect
from gpt_index import GPTMyScaleIndex, SimpleDirectoryReader

# Creating a MyScale client
client = clickhouse_connect.get_client(
    host='YOUR_CLUSTER_HOST', 
    port=8443, 
    username='YOUR_USERNAME', 
    password='YOUR_CLUSTER_PASSWORD'
)

# Load documents, build the GPTMyScaleIndex
index = GPTMyScaleIndex.from_documents(documents, myscale_client=client)
```

## ❓What to expect
MyScale is designed for storage and analysis for massive vector data with structured metadatas. If you are eager to find a high performance vector search using SQL queries, [MyScale](https://docs.myscale.com/en/vector-reference/) may be your preferred option. 
Thanks to the advantages of native structural database support, it provides you **a flexible filter** with `WHERE` clause in reader, even `JOIN` when you want to jointly search vectors with filters on relevant metadata from other tables.  `WHERE` clause is supported in `MyScaleReader`.

And it is also open for register and offers free-tier plan for you!

## 🔍 Other Apps

[HuggingFace demos](https://huggingface.co/myscale) are also available if you are curious about its realtime performance.

P.S.: If you are interested in the super secret recipe on building high performance AI+DB applications with MyScale, please visit [here](https://docs.myscale.com/en/advanced-applications/)

### CODE REVIEW

**Review by jerryjliu — APPROVED** [review]
looks pretty good, thanks for adding tests too!

**Comment by jerryjliu** [comment]
> looks pretty good, thanks for adding tests too!

@Nonegrace looks like there's some linter issues, would you be able to help fix?

**Comment by Nonegrace** [comment]
> 
fixed, also remove unused pytest annotations

**Comment by Nonegrace** [comment]
rebased main and fixed lint error again

**Review by jerryjliu — APPROVED** [review]
sweet!

**Pull request merged**
