### PR TITLE
Add Neo4j support

### PR DESCRIPTION
**Pull request by tomasonjo**
# Description

Add Neo4j support

## Type of Change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Added new unit/integration tests
- [x] Added new notebook (that tests end-to-end)
- [x] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by logan-markewich** [comment]
@tomasonjo I know you were hitting some pydantic errors right? I was able to run the code and connect to an existing db on neo4j aura. 

I suspect it's probably an env issue, I would try a fresh venv and install the minimum requirements

For example, using `venv`:
```
python -m venv venv
source venv/bin/activate
pip install llama-index neo4j
```

**Comment by tomasonjo** [comment]
The graphstore object is more or less finished. I haven't found any existing tests for NebulaGraph or Kuzu?

**Comment by logan-markewich** [comment]
@tomasonjo yea our testing... could be better haha. Feel free to attempt it, otherwise we can worry about it at another PR

The notebook can go in docs/examples/index_structs/knowledge_graph

**Comment by tomasonjo** [comment]
I've added the notebook. I am aware that I hardcoded Neo4j credentials, and that's fine.

LMK if there is anything else needed from my side.

**Comment by logan-markewich** [comment]
Thanks for the fast work on this @tomasonjo !! I think I can clean up the linting here and do some final docs stuff :) Should be able to get this merged today!

**Comment by tomasonjo** [comment]
btw... the rebel example you have is a bit buggy, but I added a fix and improved removing hallucinations along with the text2cypher for neo4j in a notebook if you want to add it somewhere:

https://github.com/tomasonjo/blogs/blob/master/llm/Llamaindex-rebel-neo4j.ipynb

**Comment by logan-markewich** [comment]
Will definitely use that notebook somewhere, thanks for patching that up!

**Comment by jerryjliu** [comment]
@tomasonjo thanks for the speed on this ⚡️

**Pull request merged**
