### PR TITLE
Doc reference for metadata

### PR DESCRIPTION
**Pull request by anoopshrma**
In Case of loading multiple Docs at once, We can use the file_name reference to specify user about the source file from which data is being extracted. 

Use Case: Provide Mendable like feature to provide the exact file from which response is generated.

### CODE REVIEW

**Review by jerryjliu — APPROVED** [review]

**Comment by jerryjliu** [comment]
@anoopshrma seems like there's some small lint errors

**Comment by anoopshrma** [comment]
> @anoopshrma seems like there's some small lint errors

Yes, will check on it

**Comment by anoopshrma** [comment]
> @anoopshrma seems like there's some small lint errors

Made the change @jerryjliu

**Comment by anoopshrma** [comment]
This is strange, I found one lint issue, fixed it. Still it is failing.

**Pull request merged**
