### PR TITLE
Updated documentation links

### PR DESCRIPTION
**Pull request by anoopshrma**
# Description

Links were not working in the following two cases.

Fixes # (issue)

## Type of Change

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- [x] I stared at the code and made sure it makes sense

### CODE REVIEW

**Comment by logan-markewich** [comment]
The preferred method here would be to use relative links, not `http` links

**Comment by anoopshrma** [comment]
Okay I see, will make the changes and push it

**Comment by anoopshrma** [comment]
Replaced http with relative link @logan-markewich

**Comment by logan-markewich** [comment]
Thanks!

**Pull request merged**
