### PR TITLE
Allow SimpleDirectoryReader to support custom file extensions

### PR DESCRIPTION
**Pull request by tilleul**
# Description

For now, SimpleDirectoryReader only supports the default file extensions as mentioned in DEFAULT_FILE_READER_CLS.
By checking if the file extension is in one of the (optional) file_extractors, we allow the developer to use the classic SimpleDirectoryReader class not only with custom readers but also with other file extensions.

## Type of Change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update (**more precisely a clarification**)

# How Has This Been Tested?
Create a directory to read and copy in there a markdown file. Rename the extension to whatever you want (for example: "new_ext_but_really_md").
Then create a `SimpleDirectoryReader` instance with a `file_extractor` dict with the new extension handled by `MarkdownReader` and call `load_data()`
```
documents = SimpleDirectoryReader(doc_folder, file_extractor={".new_ext_but_really_md": MarkdownReader() }).load_data()
```

### CODE REVIEW

**Comment by tilleul** [comment]
any idea why ?

**Comment by logan-markewich** [comment]
@tilleul just formatting error, I can take care of it actually

**Comment by tilleul** [comment]
ok I see now ... are there any guidelines for code formatting  ?

**Comment by logan-markewich** [comment]
@tilleul if you do `pip install -r requirements.txt` from the repo requirements, you can run the following to make sure everything is all formatted/linted

```
black .
ruff . --fix
mypy .
```

black and ruff do automatic formatting, mypy does type checking. Locally you'll probably get a lot of errors with mypy, but just need to make sure your changes aren't adding any new errors lol

**Pull request merged**
