### PR TITLE
add try...except... for mbox reader

### PR DESCRIPTION
**Pull request by jerryleooo**
# Description

In my mbox file exported from Gmail, there is a bad date format that can not be handled by Python's email toolkit. And this makes the whole mbox parsing fail.

We may need a simple `try...except...` outside each message handling to avoid a single parsing failure failing the whole mbox parsing.

Fixes https://github.com/jerryjliu/llama_index/issues/6247

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [x] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by logan-markewich** [comment]
Can you fix the linting here?

**Comment by jerryleooo** [comment]
Hi @logan-markewich I tried to rerun the `make lint` and the errors are from existing code:

```
(env) ➜  llama_index git:(fix-singel-mail-parsing-failure) make lint
mypy .
llama_index/readers/redis/utils.py:10: error: Library stubs not installed for "redis.client"  [import]
llama_index/readers/redis/utils.py:11: error: Library stubs not installed for "redis.commands.search.query"  [import]
llama_index/readers/redis/utils.py:11: note: Hint: "python3 -m pip install types-redis"
llama_index/vector_stores/redis.py:31: error: Library stubs not installed for "redis.client"  [import]
llama_index/vector_stores/redis.py:32: error: Library stubs not installed for "redis.commands.search.field"  [import]
llama_index/vector_stores/redis.py:90: error: Library stubs not installed for "redis"  [import]
llama_index/vector_stores/redis.py:212: error: Library stubs not installed for "redis.exceptions"  [import]
llama_index/vector_stores/redis.py:308: error: Library stubs not installed for "redis.commands.search.indexDefinition"  [import]
llama_index/vector_stores/chatgpt_plugin.py:6: error: Library stubs not installed for "requests"  [import]
llama_index/vector_stores/chatgpt_plugin.py:7: error: Library stubs not installed for "requests.adapters"  [import]
llama_index/readers/web.py:5: error: Library stubs not installed for "requests"  [import]
llama_index/readers/download.py:16: error: Library stubs not installed for "pkg_resources"  [import]
llama_index/readers/download.py:16: note: Hint: "python3 -m pip install types-setuptools"
llama_index/readers/download.py:17: error: Library stubs not installed for "requests"  [import]
llama_index/readers/make_com/wrapper.py:9: error: Library stubs not installed for "requests"  [import]
llama_index/readers/chatgpt_plugin/base.py:6: error: Library stubs not installed for "requests"  [import]
llama_index/readers/chatgpt_plugin/base.py:7: error: Library stubs not installed for "requests.adapters"  [import]
llama_index/readers/chatgpt_plugin/base.py:7: note: Hint: "python3 -m pip install types-requests"
llama_index/readers/chatgpt_plugin/base.py:7: note: (or run "mypy --install-types" to install all missing stub packages)
llama_index/readers/chatgpt_plugin/base.py:7: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
llama_index/tools/tool_spec/notion/base.py:6: error: Library stubs not installed for "requests"  [import]
llama_index/indices/common/struct_store/base.py:119: error: Need type annotation for "text_chunks" (hint: "text_chunks: List[<type>] = ...")  [var-annotated]
Found 17 errors in 9 files (checked 475 source files)
make: *** [lint] Error 1
```

I guess we can fix this in another PR and then rebase this one?

**Comment by logan-markewich** [comment]
@jerryleooo the errors are actually coming from black (it's our formatting checker)

You can run `black .`

**Comment by jerryleooo** [comment]
Hi @logan-markewich I updated the PR, can help rerun the CI?

**Pull request merged**
