### PR TITLE
add model name to langchain metadata, pass retriever service context to response synthesizer

### LINKED ISSUE #6620: [Bug]: when tree_child_branch_factor > 1, wrong OpenAI model is u
### Bug Description

I use service_context to specify model gpt-3.5-turbo, I use tree index. It works fine when tree_child_branch_factor is 1. However, when tree_child_branch_factor is 2, about half the requests to OpenAI API uses default "text-davinci-003". 

### Version

llama-index-0.6.35

### Steps to Reproduce

the code snippets:

```python
...
        predictors = {
            ModelChoice.GPT35: LLMPredictor(llm=ChatOpenAI(temperature=0.01, model_name="gpt-3.5-turbo")),
...
        predictor = predictors[model_choice]
        chunk_size = chunk_sizes[model_choice]
        return ServiceContext.from_defaults(llm_predictor=predictor, chunk_size=chunk_size)
...
            reader = SimpleDirectoryReader(input_dir=self.input_dir)
            documents = reader.load_data()
            index = GPTTreeIndex.from_documents(documents, service_context=service_context)
...
            retriever = TreeSelectLeafRetriever(index=self.index, child_branch_factor=self.tree_child_branch_factor)
            self.query_engine = RetrieverQueryEngine(retriever=retriever)
...
        query_engine_manager.query_engine.query("78890 which model is it?")

```

### Relevant Logs/Tracbacks

```shell
I use the debug log to confirm this, for example

DEBUG:openai:api_version=None data='{"prompt":  ... ... "model": "text-davinci-003", "temperature": 0.0, "max_tokens": 2367, "top_p": 1, "frequency_penalty": 0, "presence_penalty": 0, "n": 1, "logit_bias": {}}' message='Post details'
```

### PR DESCRIPTION
**Pull request by tyre**
# Description

Fixes #6620 and #6510 
Adds `model_name` to `LLMMetadata` that is automatically set when possible.

**RetrieverQueryEngine service_context param**
There are two issues here. In #6510, the service context is not being propagated when `as_query_engine` is called on an index. While it attempts to add a `service_context` argument to the call to `RetrieverQueryEngine.from_args`, `RetrieverQueryEngine.__init__` doesn't actually support a `service_context` parameter.

So this adds a `service_context` parameter to `RetrieverQueryEngine.__init__`, which fixes this.

**RetrieverQueryEngine fallback to retriever's service context**
For #6630, `RetrieverQueryEngine` was not passed any explicit `service_context`. Its only required parameter is a `retriever`. For these cases, we can fall back to that retriever's service context. The `BaseReceiver` will try to calculate a service context since these can be stored directly or on the index depending on the type.

**Add model_name to LLMMetadata**
One of the challenges in testing this was that the model name for an instance of an LLM isn't easily accessible. When users were trying to debug their code, it's non-obvious that the wrong model is being used.

To simplify this, I've added a `model_name` to `LLMMetadata` and we'll automatically set it when possible.

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Added new unit/integration tests
- [x] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by logan-markewich** [comment]
@tyre I'm curious why the retriever query engine needs the service context on the init? The LLM and embedding models are not actually used in the class -- everything happens in the response synthesizer and retriever

**Comment by logan-markewich** [comment]
Yea, pulling from the retriever is fine, just doesn't need to be added to the object class itself I think

**Comment by tyre** [comment]
@logan-markewich alright that's done, lmk what you think

**Review by logan-markewich — APPROVED** [review]
Looks good, sorry for the delay on this! Appreciate the effort to ensure the service context is passed around a little better 💪🏻

**Pull request merged**
