### PR TITLE
Feat qdrant metadata filtering

### PR DESCRIPTION
**Pull request by kacperlukawski**
# Description

Qdrant has built-in filtering capabilities which weren't reflected in Llama Index. This PR introduces that mechanism to the Qdrant vector store. 

In addition to that, I fixed the `ExactMatchFilter` implementation. It was using `Union[str, int, float]` instead of strict types what was resulting in a wrong type when applying integers or floats (or all were converted to strings). `ExactMatchFilter(key="test", value=1)` was converted to `ExactMatchFilter(key="test", value="1")`.

For reference: https://docs.pydantic.dev/latest/usage/types/#strict-types

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

The unit tests are included. They cover all the supported types.

- [x] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [ ] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by kacperlukawski** [comment]
@NirantK I'd appreciate your review on that

**Comment by NirantK** [comment]
@kacperlukawski is there a way for me/Llama Index users to try this API e.g. a Jupyter notebook or tests?

**Comment by kacperlukawski** [comment]
@NirantK Tests are included in the PR. Besides, it works the same way as in all the other vector stores, so I didn't include any notebook. Do you think it's essential to have one?

**Comment by logan-markewich** [comment]
@kacperlukawski sorry for the delay on looking at this. Is this good to go from your point of view?

**Comment by kacperlukawski** [comment]
@logan-markewich Yes, this is a relatively simple change, but much awaited by our users. To my mind, this is ready to be released.

**Pull request merged**
