### PR TITLE
update paths on .md files

### PR DESCRIPTION
**Pull request by Valentina-Frenkel**
Add `/docs` to the corresponding paths in the markdown file.

# Description

It appears that some folders were moved to the `/docs` folder, which caused relative paths in markdown files referencing them to stop working. I ran a script to check all the relative paths in `.md` files that reference any of the folders inside `/docs`: `core_modules`, `community`, `getting_started`, `end_to_end_tutorials`, `examples`, `api_reference`, `development`, `_static`. The script checks all the .md files and verifies if a relative path to these folders is used. If so, it adds the corresponding prefix `/docs` to them. This action fixes broken links and images in the `.md` files.

## Type of Change
- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
Broke links and images are now working.

### CODE REVIEW

**Comment by logan-markewich** [comment]
Thanks for looking into this!

Curious though -- which links weren't working? As far as I know, the `/docs` prefix isn't needed because the docs are all built relative to that folder

For example, the `The full set of supported LLMs are found here.` link from [this page](https://gpt-index.readthedocs.io/en/stable/community/integrations.html) was updated in this PR, but the link currently works on the live docs

**Comment by Valentina-Frenkel** [comment]
Links at the .md files at the github repo. For example [this one](https://github.com/jerryjliu/llama_index/blob/main/examples/multimodal/data/llama/index_guide.md) does not show the pictures or link to the correct .md file.

**Comment by logan-markewich** [comment]
@Valentina-Frenkel ah yea, the examples in the top-level `examples` folder are kind of un-maintained. Can you edit your PR to only change the links in notebooks that are in that folder?

**Comment by Valentina-Frenkel** [comment]
What about the other .md files at `/doc` folder? as [docs/core_modules/data_modules/node_parsers/usage_pattern.md](https://github.com/jerryjliu/llama_index/blob/5a44a572c7b2d68d3ef75b53137dceb9c33f6275/docs/core_modules/data_modules/node_parsers/usage_pattern.md) or [docs/community/integrations.md](https://github.com/jerryjliu/llama_index/blob/5a44a572c7b2d68d3ef75b53137dceb9c33f6275/docs/community/integrations.md)? Links there are also not working. Let me know how to prepare a new PR accordingly.

**Comment by logan-markewich** [comment]
@Valentina-Frenkel so those links/pages are meant to be viewed on our docs page

And in that website, all the links seem to be working. For example, you linked the usage pattern file above. On the website, all links work on that page
https://gpt-index.readthedocs.io/en/stable/end_to_end_tutorials/usage_pattern.html

So, I don't think anything in the `docs/` folder needs to be updated.

If you wanted to be super thorough, you could build the docs locally and read the logs for broken links, but it's very verbose with other unimportant errors 
https://gpt-index.readthedocs.io/en/stable/development/documentation.html

**Comment by Valentina-Frenkel** [comment]
Thank you for your guidance @logan-markewich. I misunderstood the context of the file usage. I have now reverted the changes in the /docs folder and have updated the links only in the top-level examples folder, as you suggested. I appreciate your patience :)

**Comment by logan-markewich** [comment]
@Valentina-Frenkel no worries, thanks for fixing this! 💪🏻

**Pull request merged**
