### PR TITLE
Use algolia search in docs 

### PR DESCRIPTION
**Pull request by Disiok**
Motivation: Default search box kinda sucks, Mendable is slow
Played around with Algolia search box, kinda nice? 🤷 

Screenshot 2023-07-10 at 11 52 42 PM

Screenshot 2023-07-10 at 11 53 03 PM

### CODE REVIEW

**Review by jerryjliu — APPROVED** [review]

**Comment by Disiok** [comment]
Some issues: 
1. searchbar doesn't turn dark mode when page turns dark mode
2. command + K shortcut clashes with Mendable 😢

**Comment by logan-markewich** [comment]
Possible dark mode hacks? https://discourse.algolia.com/t/dynamic-dark-mode-support-a-la-media-prefers-color-scheme-dark/15004/6

**Comment by logan-markewich** [comment]
Yea the dark mode is unfortunate. I'll quickly try to see if I can hack it

The search is also slightly outdated (some links are 404). Not sure how it works for refreshing

**Comment by logan-markewich** [comment]
There we go, CSS should be much nicer in dark mode now

**Comment by logan-markewich** [comment]
huh weird, it works locally but not on the docs preview 🤔

**Pull request merged**
