### PR TITLE
Add support for Pinecone Starter Tier

### PR DESCRIPTION
**Pull request by ivanazeljkovic**
# Description

Pinecone Starter Tier changes: 
- remove namespaces
- remove delete by metadata feature

Resolves: [Pinecone - support Starter Tier #6822](https://github.com/jerryjliu/llama_index/issues/6822)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [x] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by jamescalam** [comment]
@logan-markewich there isn't a similar feature coming — the best alternative is to add a "namespace" metadata field and simply use metadata filters for each namespace, the resultant behavior is equal

**Comment by logan-markewich** [comment]
@jamescalam that may help yea. Using the metadata filters isn't quite as convenient for users as settings the namespace when creating the vector store object

But I'm curious what will happen to users that have existing pinecone indexes with the old version? Will they get upgraded/migrated automatically?

**Comment by jamescalam** [comment]
@logan-markewich my bad — this is specific to upcoming changes on the Pinecone starter plan (free tier), this actually won't affect other plans or existing indexes

With that in mind, this PR isn't ready, we need to make further changes first, sorry!

**Comment by Disiok** [comment]
Hey @ivanazeljkovic @jamescalam  just gently checking what the status is for this PR? Could we close this and re-open in the future if it's not quite ready yet?

**Comment by logan-markewich** [comment]
Hey @ivanazeljkovic @jamescalam I am going to close this PR for now since it seems to have stalled out. Feel free to re-open it if your plans change otherwise!

**Pull request closed without merging**
